// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qiiuvnktbjbggdptybxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaXV2bmt0YmpiZ2dkcHR5YnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MjQ4NDksImV4cCI6MjA3NzMwMDg0OX0.2DcG3fZ_vSE1d83bZZ5YtE7Q_HwBCY04zIpK7Ev24Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);